openapi: '3.0.0'
info:
  title: Microservice Boilerplate
  version: '1.0.0'

servers:
  - url: http://localhost:3000
    description: Development server

paths:
  /health:
    $ref: ./paths/health.yaml

  /login:
    $ref: ./paths/login.yaml
